# Generated by Django 5.0.4 on 2024-04-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipificacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_padre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tipificaciones',
            },
        ),
    ]
