# Generated by Django 5.0.4 on 2024-04-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipificacion',
            name='id_padre',
        ),
        migrations.RemoveField(
            model_name='tipificacion',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='tipificacion',
            name='id',
            field=models.CharField(db_column='id', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tipificacion',
            name='id_Padre',
            field=models.CharField(blank=True, db_column='idPadre', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipificacion',
            name='Nombre',
            field=models.CharField(db_column='Nombre', default='names', max_length=255, null=True),
        ),
    ]
