# Generated by Django 5.0.4 on 2024-04-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_tipificacion_id_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipificacion',
            name='id_Padre',
            field=models.CharField(db_column='idPadre', default='idfathers', max_length=255, null=True),
        ),
    ]
