# Generated by Django 5.0.4 on 2024-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_tipificacion_id_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipificacion',
            name='Nombre',
            field=models.CharField(db_column='Nombre', default='names', max_length=255),
        ),
    ]
