# Generated by Django 5.0.4 on 2024-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_tipificacion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipificacion',
            old_name='id_Padre',
            new_name='idPadre',
        ),
        migrations.AlterField(
            model_name='tipificacion',
            name='Nombre',
            field=models.CharField(db_column='Nombre', default='names', max_length=255, null=True),
        ),
    ]
