# Generated by Django 5.0.4 on 2024-04-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_rename_id_padre_tipificacion_idpadre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipificacion',
            name='Nombre',
            field=models.CharField(db_column='Nombre', default='names', max_length=255),
        ),
    ]
