# Generated by Django 5.0.4 on 2024-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_registrocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField(null=True)),
                ('rut', models.CharField(max_length=20, null=True)),
                ('ruteje', models.CharField(max_length=11, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('glosa', models.CharField(max_length=255, null=True)),
                ('feccomp', models.DateField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('respuesta', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=2, null=True)),
                ('uniqueid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'All_Contacts',
            },
        ),
        migrations.AlterModelTable(
            name='registrocontacto',
            table='Registro_Contacto_copy',
        ),
    ]
