# Generated by Django 5.0.4 on 2024-04-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_allcontacts_alter_registrocontacto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontacts',
            name='feccomp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='glosa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='lead_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='respuesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='ruteje',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='tipo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='allcontacts',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='allcontacts',
            table='All_Contacts_copy',
        ),
    ]
