# Generated by Django 5.0.4 on 2024-04-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_allcontacts_feccomp_alter_allcontacts_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allcontacts',
            table='All_Contacts',
        ),
    ]
