# Generated by Django 5.0.4 on 2024-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_allcontacts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDocumento', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('fecha_emi', models.DateField(blank=True, default=None, null=True)),
                ('fecha_venc', models.DateField(blank=True, default=None, null=True)),
                ('TotalComprobante', models.IntegerField(blank=True, default=None, null=True)),
                ('NumeroComprobante', models.IntegerField(blank=True, default=None, null=True)),
                ('NumeroComprobanteFiscal', models.IntegerField(blank=True, default=None, null=True)),
                ('TipoComprobanteFiscal', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('Nombre', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Morosidad', models.IntegerField(blank=True, default=None, null=True)),
                ('Calle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Numero', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('DetalleDomicilio', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('id_documentos', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Email', models.TextField(blank=True, default=None, null=True)),
                ('Fono', models.TextField(blank=True, default=None, null=True)),
                ('Tipo_Envio', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tipo_cobranza', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('emp_cobranza_id', models.IntegerField(blank=True, default=None, null=True)),
                ('nom_emp_cobra', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('refi', models.IntegerField(blank=True, default=None, null=True)),
                ('pago0', models.IntegerField(blank=True, default=None, null=True)),
                ('dic20', models.IntegerField(blank=True, default=None, null=True)),
                ('dicom', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Cartera',
            },
        ),
    ]
