# Generated by Django 5.0.4 on 2024-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_cartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipificacion',
            name='idrespuesta',
            field=models.CharField(db_column='idrespuesta', default='idrespuesta', max_length=255, null=True),
        ),
    ]
