# Generated by Django 5.0.4 on 2024-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_tipificacion_idrespuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartera',
            name='Calle',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='DetalleDomicilio',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='Fono',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='Morosidad',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='NumeroComprobante',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='NumeroComprobanteFiscal',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='NumeroDocumento',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='TipoComprobanteFiscal',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='Tipo_Envio',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='TotalComprobante',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='dic20',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='dicom',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='emp_cobranza_id',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='fecha_emi',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='fecha_venc',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='id_documentos',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='nom_emp_cobra',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='pago0',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='refi',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='tipo_cobranza',
        ),
        migrations.AddField(
            model_name='cartera',
            name='cantidad_folios',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='celular',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='cta_cto',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='dias_mora',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='empresa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='fec_emi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='fec_vcto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='folio',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='fono_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='fono_3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='fono_4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='tipo_convenio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='tipo_doc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='tramo_mora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartera',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartera',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
