# Generated by Django 5.0.4 on 2024-05-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_remove_cartera_calle_remove_cartera_detalledomicilio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartera',
        ),
    ]
