# Generated by Django 5.0.4 on 2024-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_delete_cartera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_cto', models.CharField(blank=True, max_length=16, null=True)),
                ('rut', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('folio', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fec_emi', models.DateField(blank=True, null=True)),
                ('fec_vcto', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.BigIntegerField(blank=True, null=True)),
                ('fono_2', models.BigIntegerField(blank=True, null=True)),
                ('fono_3', models.BigIntegerField(blank=True, null=True)),
                ('fono_4', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_doc', models.CharField(blank=True, max_length=2, null=True)),
                ('dias_mora', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tramo_mora', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_convenio', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad_folios', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('empresa', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Cartera',
            },
        ),
    ]
