# Generated by Django 5.0.4 on 2024-05-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_cartera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartera',
            old_name='cta_cto',
            new_name='ctacto',
        ),
    ]
