# Generated by Django 5.0.4 on 2024-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_rename_cta_cto_cartera_ctacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('CtaCto', models.CharField(blank=True, max_length=16, null=True)),
                ('boletas', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vence', models.DateField(blank=True, null=True)),
                ('vence1', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cartera_Totales',
            },
        ),
    ]
