# Generated by Django 5.0.4 on 2024-05-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_carteratotales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='rutdv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='registrocontacto',
            table='Registro_Contacto',
        ),
    ]
