# Generated by Django 5.0.4 on 2024-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_cartera_rutdv_alter_registrocontacto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteratotales',
            name='rutdv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
