# Generated by Django 5.0.4 on 2024-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_carteratotales_rutdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipificacion',
            name='status',
            field=models.CharField(db_column='status', default='status', max_length=255, null=True),
        ),
    ]
