# Generated by Django 5.0.4 on 2024-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_tipificacion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocontacto',
            name='idrespuesta',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
