# Generated by Django 5.0.4 on 2024-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_alter_registrocontacto_idrespuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocontacto',
            name='idrespuesta',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
