# Generated by Django 5.0.4 on 2024-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_alter_registrocontacto_idrespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeGestionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_gestion', models.DateTimeField()),
                ('agente', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fec_compromiso', models.DateField()),
                ('glosa', models.TextField()),
            ],
            options={
                'db_table': 'vw_informe_gestion_diaria',
                'managed': False,
            },
        ),
    ]
