# Generated by Django 5.0.4 on 2024-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_informegestiondiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContactoAcsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('idrespuesta', models.CharField(blank=True, max_length=3, null=True)),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('ruteje', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('glosa', models.CharField(blank=True, max_length=255, null=True)),
                ('numdoc', models.IntegerField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('feccomp', models.DateField(blank=True, null=True)),
                ('estcomp', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tipocomp', models.IntegerField(blank=True, null=True)),
                ('abono', models.CharField(blank=True, max_length=255, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=20, null=True)),
                ('modo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Registro_Contacto',
                'managed': False,
            },
        ),
    ]
