# Generated by Django 5.0.4 on 2024-05-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0026_registrocontactoacsa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroContactoAcsa',
        ),
    ]
