# Generated by Django 5.0.4 on 2024-05-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_delete_registrocontactoacsa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipificacion',
        ),
    ]
