# Generated by Django 5.0.4 on 2024-05-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0028_delete_tipificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroContacto',
        ),
    ]
