# Generated by Django 5.0.4 on 2024-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0029_delete_registrocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField(null=True)),
                ('idrespuesta', models.IntegerField(max_length=11, null=True)),
                ('rut', models.CharField(max_length=11, null=True)),
                ('ruteje', models.CharField(max_length=12, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('glosa', models.CharField(max_length=255, null=True)),
                ('numdoc', models.IntegerField(null=True)),
                ('monto', models.IntegerField(null=True)),
                ('feccomp', models.DateField(null=True)),
                ('estcomp', models.CharField(max_length=20, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('tipocomp', models.IntegerField(null=True)),
                ('abono', models.CharField(max_length=255, null=True)),
                ('uniqueid', models.CharField(max_length=20, null=True)),
                ('modo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Registro_Contacto',
            },
        ),
    ]
