"""
Django settings for ApiRest project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(gwrlu0b4i0rq(c877@2wd=swn27!b)n%n#(lash(%v$g0tjhk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['apirest.k-3.cl', 'apirest.k-3.cl:3000']

CORS_ALLOWED_ORIGINS = [
    'https://www.k-3.cl',
    'http://localhost:5173'
    
]
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-token',  # Agregar el header personalizado
    'x-requested-with',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Api',
    'corsheaders',
    'channels',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'Api.k3.middlewares.validateJWT.JWTMiddleware',
    'Api.k3.middlewares.db_cleannup.CloseDBConnectionsMiddleware',
    
]


ROOT_URLCONF = 'ApiRest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ApiRest.wsgi.application'
ASGI_APPLICATION = 'ApiRest.asgi.application'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.grupokonectados.cl'  # Reemplaza con tu servidor SMTP, por ejemplo, 'smtp.gmail.com' para Gmail
EMAIL_PORT = 587                      # El puerto SMTP. 587 para TLS o 465 para SSL
EMAIL_USE_TLS = True                  # Si utilizas TLS
EMAIL_USE_SSL = False                 # Asegúrate de que EMAIL_USE_TLS y EMAIL_USE_SSL no estén ambos en True
EMAIL_HOST_USER = 'informacion@grupokonectados.cl'  # Tu dirección de correo electrónico
EMAIL_HOST_PASSWORD = 'Agosto2024//.,'     # Tu contraseña de correo electrónico
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER     # El correo por defecto desde el cual se enviarán los emails


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_ROUTERS = ['routers.DatabaseRouter']
# Definición de parámetros comunes
COMMON_DATABASE_CONFIG = {
    'ENGINE': 'mssql',
    'USER': 'UsrCRM',
    'PASSWORD': 'KYuOcPA5R5Yn',
    'HOST': '192.168.5.12',
    'PORT': '',  
    'OPTIONS': {
        'driver': 'ODBC Driver 17 for SQL Server',
    }
}


DATABASES = {
    'default': {**COMMON_DATABASE_CONFIG, 'NAME': 'VNORTE'},
    'svia': {**COMMON_DATABASE_CONFIG, 'NAME': 'SVIA'},
    'global': {**COMMON_DATABASE_CONFIG, 'NAME': 'GLOBAL'},
    'avo': {**COMMON_DATABASE_CONFIG, 'NAME': 'AVO'},
    'acsa': {**COMMON_DATABASE_CONFIG, 'NAME': 'ACSA'},
    'cnorte': {**COMMON_DATABASE_CONFIG, 'NAME': 'CNORTE'},
    'vsur': {**COMMON_DATABASE_CONFIG, 'NAME': 'VSUR'},
    'report': {**COMMON_DATABASE_CONFIG, 'NAME': 'report00'},
    'vici': {**COMMON_DATABASE_CONFIG, 'NAME': 'VICI'},
    'condeza': {**COMMON_DATABASE_CONFIG, 'NAME': 'CONDEZA'},
    'knet': {**COMMON_DATABASE_CONFIG, 'NAME': 'konexnet'},
    'pass': {**COMMON_DATABASE_CONFIG, 'NAME': 'RPASS'},
    'storage': {**COMMON_DATABASE_CONFIG, 'NAME': 'STORAGE'},
    'config_ssis': {**COMMON_DATABASE_CONFIG, 'NAME': 'CONFIG_SSIS'},
    'main': {**COMMON_DATABASE_CONFIG, 'NAME': 'MAIN'},
    'api': {
        'ENGINE': 'mssql',
        'NAME':'API',
        'USER': 'Admi',
        'PASSWORD': 'Kon3ctados2024',
        'HOST': '192.168.5.18',
        'PORT': '',  
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        }
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),  # Duración del token de acceso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Duración del token de actualización
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'



TIME_ZONE = 'America/Santiago'  # O la zona horaria que corresponda

USE_I18N = True

USE_TZ = True


CORS_ALLOW_ALL_ORIGINS = True


# settings.py

FILE_ATTRIBUTE_NORMAL = 0x80

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
